### ISSUE TITLE
Algumas sugestões

### ISSUE THREAD

**Issue by lucasdotvin** [linneudm/redimensionador-de-imagens#1]
Analisei o código e meus parabéns, está ótimo. Pensei apenas em algumas coisas que podem melhorá-lo e, quem sabe, ter utilidade no futuro.
* O módulo `os` tem um módulo interno chamado `path` (`os.path`), com funções úteis para trabalhar com caminhos e nomes de arquivos. Recomendo dar uma olhada nele, o uso é super simples; especialmente na função `splitext()`, que divide um nome de arquivo em uma lista [nome, extensão], o que pode facilitar o processo realizado nas linhas 16 ~ 22.
* Em vez de usar um bloco `try` (que têm certo custos de execução) para criar a pasta onde as imagens serão salvas, você poderia usar o método `os.makedirs()` e passar o parâmetro `exist_ok` como True; assim o Python não cria exceções caso a pasta já exista.

É isso. Parabéns pelo código! Já passei pela necessidade de ter que redimensionar várias imagens, é triste kkkk

**Comment by linneudm** [comment]
Hahahah muito bom! Vou fazer as alterações agora. Valeu pela dica amigo.
